### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by lrs8810** [lrs8810/olympic_api#4]
Add `.travis.yml` file to root directory with the following: 
```
language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database olympic_api_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 
  app: 
  on:
    repo: 
env:
  global:
  - secure: 
  - secure: 
  - secure: 
  - secure: 
```
